baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Persephone.meow'
theme = 'aps-journal'
type = 'post'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[Params]
  math = true
  plotly = true
  search = true
  tagFilter = true

[Params.DropCap]
  Enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['\(', '\)']]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    codeFences = true
    guessSyntax = false
    noClasses = false